In [1]:
import pandas as pd
import numpy as np
import glob
from sklearn.metrics.cluster import adjusted_rand_score, normalized_mutual_info_score, homogeneity_score, completeness_score
import seaborn as sns

In [3]:
def get_dataname(data_dir):
    dname = data_dir.split('/')[-1]
    if 'Maynard' in dname:
        return(dname[7:-4])
    if 'Dataosmfish' in dname:
        return ('osmfish')
    if 'BaristaSeq' in dname:
        return(dname[10:-12])
    if 'BZ' in dname:
        return(dname[7:-4])
    if '1k' in dname:
        return ('STARmap_20180505_BY3_1k')
    if 'global' in dname:
        return(dname[7:-4])
    if 'MERFISH' in dname:
        return (dname[7:-4])
    if 'MsBrainAgingSpatialDonor' in dname:
        return (dname[:-4])

In [5]:
test_dir = '/Users/melancholy/Desktop/results section b and c/MsBrainAgingSpatialDonor_10Slice0.csv'
dname = test_dir.split('/')[-1]
print(dname, get_dataname(test_dir))

MsBrainAgingSpatialDonor_10Slice0.csv MsBrainAgingSpatialDonor_10Slice0

In [7]:
data_dir_full = []

for data in glob.glob("/Users/melancholy/Desktop/results section b and c/B*.csv", recursive=True):
    data_dir_full.append(data)
for data in glob.glob("/Users/melancholy/Desktop/results section b and c/May*.csv", recursive=True):
    data_dir_full.append(data)
for data in glob.glob("/Users/melancholy/Desktop/results section b and c/D*.csv", recursive=True):
    data_dir_full.append(data)
for data in glob.glob("/Users/melancholy/Desktop/results section b and c/MER*.csv", recursive=True):
    data_dir_full.append(data)
for data in glob.glob("/Users/melancholy/Desktop/results section b and c/o*.csv", recursive=True):
    data_dir_full.append(data)
for data in glob.glob("/Users/melancholy/Desktop/results section b and c/s*.csv", recursive=True):
    data_dir_full.append(data)

In [9]:
data_vec = []
method_vec = []
ARI_vec = []
NMI_vec = []
HOM_vec = []
COM_vec = []

for data_dir in data_dir_full:
    # print(data_dir)
    df = pd.read_csv(data_dir)

    data_vec.append(get_dataname(data_dir))
    method_vec.append('GraphBG')
    ARI_vec.append(adjusted_rand_score(df['GraphBGMv3a2tied'], df['ground_truth']))
    NMI_vec.append(normalized_mutual_info_score(df['GraphBGMv3a2tied'], df['ground_truth']))
    HOM_vec.append(homogeneity_score(df['GraphBGMv3a2tied'], df['ground_truth']))
    COM_vec.append(completeness_score(df['GraphBGMv3a2tied'], df['ground_truth']))
    
    # GraphST
    data_vec.append(get_dataname(data_dir))
    method_vec.append('GraphST')
    ARI_vec.append(adjusted_rand_score(df['GraphST'], df['ground_truth']))
    NMI_vec.append(normalized_mutual_info_score(df['GraphST'], df['ground_truth']))
    HOM_vec.append(homogeneity_score(df['GraphST'], df['ground_truth']))
    COM_vec.append(completeness_score(df['GraphST'], df['ground_truth']))
    
df_full = pd.DataFrame({'DataName': data_vec, 'Method': method_vec, 'ARI': ARI_vec, 'NMI': NMI_vec, 'HOM': HOM_vec, 'COM': COM_vec})

In [11]:
# df_full.head(1)
df_full.to_csv('all_results.csv')

In [13]:
df_full

                 DataName   Method       ARI       NMI       HOM       COM
0                 Slice_3  GraphBG  0.404763  0.530126  0.590045  0.481255
1                 Slice_3  GraphST  0.450845  0.543609  0.613666  0.487908
2                 Slice_1  GraphBG  0.665301  0.711759  0.746669  0.679968
3                 Slice_1  GraphST  0.663214  0.719770  0.775065  0.671840
4                 Slice_2  GraphBG  0.735513  0.774360  0.795635  0.754192
..                    ...      ...       ...       ...       ...       ...
57   20180417_BZ5_control  GraphST  0.282487  0.468369  0.542098  0.412295
58  20180424_BZ14_control  GraphBG  0.771893  0.723005  0.717062  0.729047
59  20180424_BZ14_control  GraphST  0.723782  0.673002  0.660726  0.685742
60   20180419_BZ9_control  GraphBG  0.540438  0.571023  0.682814  0.490686
61   20180419_BZ9_control  GraphST  0.533455  0.546090  0.628523  0.482773

[62 rows x 6 columns]

In [15]:
df_full.groupby(['Method']).mean(numeric_only=True)

              ARI       NMI       HOM       COM
Method
GraphBG  0.511841  0.610008  0.643069  0.585703
GraphST  0.456973  0.583776  0.597536  0.576827

In [19]:
df_origin = pd.read_csv('/Users/melancholy/Desktop/results section b and c/41592_2024_2215_MOESM6_ESM.csv')
df_bm = df_origin[['DataName', 'Method', 'NMI', 'HOM', 'COM']]
df_bm = df_bm.loc[df_bm.DataName.isin(np.unique(data_vec))]

     DataName Method       NMI       HOM       COM
10    Slice_1   BASS  0.711096  0.671577  0.755557
11    Slice_1   BASS  0.711096  0.671577  0.755557
12    Slice_1   BASS  0.711096  0.671577  0.755557
13    Slice_1   BASS  0.711096  0.671577  0.755557
14    Slice_1   BASS  0.711096  0.671577  0.755557
...       ...    ...       ...       ...       ...
3747  Slice_2   BASS  0.816240  0.822387  0.810183
3748  Slice_2   BASS  0.816240  0.822387  0.810183
3749  Slice_2   BASS  0.816240  0.822387  0.810183
3750  Slice_2   BASS  0.816240  0.822387  0.810183
3751  Slice_2   BASS  0.816240  0.822387  0.810183

[3642 rows x 5 columns]

In [25]:
df_partial = df_full[['DataName', 'Method', 'NMI', 'HOM', 'COM']]
df_concat = pd.concat([df_partial, df_bm])
df_concat = df_concat[df_concat.Method != 'BayesSpace']
df_concat = df_concat.loc[
    df_concat.DataName.isin(np.unique(data_vec)) & 
    ~df_concat.Method.isin(["leiden", "SpaGCN_with"])
]
df_concat["Method"] = df_concat["Method"].replace("conST_nopre", "conST")
df_concat["Method"] = df_concat["Method"].replace("SpaGCN_without", "SpaGCN")

Remove BayesSpace

In [27]:
df_concat

     DataName   Method       NMI       HOM       COM
0     Slice_3  GraphBG  0.530126  0.590045  0.481255
1     Slice_3  GraphST  0.543609  0.613666  0.487908
2     Slice_1  GraphBG  0.711759  0.746669  0.679968
3     Slice_1  GraphST  0.719770  0.775065  0.671840
4     Slice_2  GraphBG  0.774360  0.795635  0.754192
...       ...      ...       ...       ...       ...
3747  Slice_2     BASS  0.816240  0.822387  0.810183
3748  Slice_2     BASS  0.816240  0.822387  0.810183
3749  Slice_2     BASS  0.816240  0.822387  0.810183
3750  Slice_2     BASS  0.816240  0.822387  0.810183
3751  Slice_2     BASS  0.816240  0.822387  0.810183

[3164 rows x 5 columns]

In [31]:
df_concat.to_csv("result_metrics_various.csv", index=False)

In [33]:
print(np.unique(df_origin[df_origin.Method=='BayesSpace']['DataName']))

['151507' '151508' '151509' '151510' '151669' '151670' '151671' '151672'
 '151673' '151674' '151675' '151676']

In [35]:
print(np.unique(df_concat[df_concat.Method=='BASS']['DataName']))

['151507' '151508' '151509' '151510' '151669' '151670' '151671' '151672'
 '151673' '151674' '151675' '151676' '20180417_BZ5_control'
 '20180419_BZ9_control' '20180424_BZ14_control' 'MERFISH_0.04'
 'MERFISH_0.09' 'MERFISH_0.14' 'MERFISH_0.19' 'MERFISH_0.24'
 'STARmap_20180505_BY3_1k' 'Slice_1' 'Slice_2' 'global_z0' 'global_z1'
 'global_z2' 'global_z3' 'global_z4' 'osmfish']